# -*- coding: utf-8 -*-

from os import PathLike
from abc import abstractmethod
from .fixer import Fixer


class DirFixer(Fixer):
    """A fixer for fixs directories that generated by java decompilers."""

    @abstractmethod
    def fix(self, aDir: PathLike):
        pass

