# -*- coding: utf-8 -*-

from abc import ABC, abstractmethod
from .fixer import Fixer


class SrcFixer(Fixer):
    """The source fixer for fixs the java file that generated by java
    decompilers."""

    @abstractmethod
    def fix(self, source: str):
        """Return source string if we have a fix, otherwise exception raised
        """
        pass

